
%
% NOTE -- ONLY EDIT THE .Rnw FILE!!!  The .tex file is
% likely to be overwritten.
%

%\VignetteIndexEntry{ceu1kg overview}
%\VignetteDepends{GGtools, snpMatrix}
%\VignetteKeywords{genetics}
%\VignettePackage{ceu1kg}

\documentclass[12pt]{article}

\usepackage{amsmath,pstricks}
\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}


\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}


\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rfunarg}[1]{{\texttt{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}

\textwidth=6.2in

\bibliographystyle{plainnat} 
 
\begin{document}
%\setkeys{Gin}{width=0.55\textwidth}

\title{\textit{ceu1kg}: resources for exploring the 1000 genomes data on
individuals of central European ancestry in Bioconductor}
\author{VJ Carey}
\maketitle

\section{Introduction}
Using results of next generation sequencing experiments,
a consortium of geneticists produced calls for SNP at approximately 8 million loci of the genomes of individuals of central European ancestry.

Genotype calls are held in a list of snp.matrix instances:
<<lkd>>=
library(ceu1kg)
if (!exists("ceu1kg.sml")) data(ceu1kg.sml)
names(ceu1kg.sml)
ceu1kg.sml[[1]]
@

\clearpage

Metadata about the loci are provided in GRanges instances:
<<lkm>>=
if (!exists("ceu1kgMeta_20")) data(ceu1kgMeta_20)
ceu1kgMeta_20[1:3]
@

The Bioconductor \textit{GGdata} package includes HapMap phase II genotypes on 90
CEU individuals in 30 trios, coupled with expression data as distributed
at the Sanger GENEVAR project (\url{ftp://ftp.sanger.ac.uk/pub/genevar/}).  
The 1KG genotypes are available for 43 of these 90 and the associated
genotype plus expression data for these 43 are stored in an `smlSet' container:
<<lkg>>=
if (.Platform$OS.type != "windows") {
data(ceu1kg)
ceu1kg
}
@

\section{Session information}
<<lks>>=
sessionInfo()
@

\end{document}
